"""cut the user role

Revision ID: 77693b4be7db
Revises: 
Create Date: 2025-11-04 11:53:10.674636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77693b4be7db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("driver_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        "fk_order_driver_id_driver",
        "order",
        "driver",
        ["driver_id"],
        ["id"],
        ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_order_driver_id_driver", "order", type_="foreignkey")
    op.drop_column("order", "driver_id")
    # ### end Alembic commands ###
